### ISSUE TITLE
新歓特設ページの設定

### ISSUE THREAD

**Issue by tsume-ha** [snakagaw/unplugged-hp#34]
通常の新歓が開催できない可能性が高いので、HPにライブ動画を載せ、新入生に見てもらう。

LiveLogを一般に公開するのは避けたいのです…（一般公開設定してなくても、見られたくないものは多い）

目標

- YouTube動画を載せる

課題

- 動画の羅列にする？ライブごとにまとめる？

**Comment by snakagaw** [comment]
- 新歓用のプレイリストを作成して, アップロードし直すのも選択肢かも. 一度公開すると、限定公開には戻せないので．

**Comment by sinnta123** [comment]
新歓用のプレイリストを作成する予定でしたので、中川さんの案が良いかもしれません。

**Comment by tsume-ha** [comment]
再アップロードは良いかもしれませんね

**Comment by tsume-ha** [comment]
同じ動画をアップロードするとyoutube側に弾かれました...
なので動画自体は限定公開にしておいて、プレイリストだけ公開したいと思うのですがどうでしょう？

**Comment by snakagaw** [comment]
別アカウントもだめそうですかね? ならプレイリスト公開でもいいと思います

**Comment by tsume-ha** [comment]
別アカウントは試してません...
が、動画自体は限定公開のままにしておいて、n月ライブのプレイリストと新歓用のプレイリストの両方に動画入れたうえで、新歓用プレイリストを公開する、
という流れでいいかなぁと
